name: CI PyTests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry & Tox
        run: pip install poetry tox

      - name: Install Dependencies
        run: poetry install

      - name: Run Tox
        run: tox -e py310
